### ISSUE TITLE
trying mongosql 

### ISSUE THREAD

**Issue by younes200** [master/mongosql#1]
Hi,
I'm trying to use mongosql with ejabberd but i get exception when tape :

```
{ok, Pool} = mongosql_conn:start("127.0.0.1", 27017, "test1").
** exception error: no match of right hand side value ok
```

I think it's one of the cause my ejabberd not workiing when I use emongo odbc config.
Thank you in advance for your reply.

**Comment by master** [comment]
Could you show an output of mongosql_conn:start? I.e. the result of

```
mongosql_conn:start("127.0.0.1", 27017, "test1").
```

Also, please make sure emongo app has been started.

**Comment by younes200** [comment]
It seems that I was using a old version of emongo, I tried with your reposit from https://github.com/master/emongo I and now it works.
 Thank you for your reply.
