### ISSUE TITLE
Fetch returns null

### ISSUE THREAD

**Issue by younes200** [master/mongosql#2]
Hi,
It seems that _mongosql_conn:fetch_ will returns null if the sync parameter is true, here is example :

``` erlang
3> mongosql_conn:fetch(Pool, "insert into users username, password values ('test', 'test');", false).
{updated,1}
4> mongosql_conn:fetch(Pool, "insert into users username, password values ('test', 'test');", true). 
{error,null}
```

**Comment by master** [comment]
mongosql_conn:fetch will return null, if sync parameter is true and transaction has failed. That's the idea behind sync parameter. Is your MongoDB up & running? Is eMongo working correctly?

**Comment by younes200** [comment]
Ok, I understand, when using mongosql with ejabberd, the request failed when used in transaction 
https://github.com/master/ejabberd/blob/v2.1.6-mongo/src/odbc/ejabberd_odbc.erl#L445
That why the command _ejabberdctl register test localhost test_ failed
